# Bystander: 视频流量模型 ——>>> 播放器缓冲状态

In [117]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [118]:
#流的输入代表了数据的无结构化传递，按照流的方式进行输入输出，数据被当成无结构的字节序或字符序列
from io import StringIO

In [119]:
#数据预处理、归一化。大多数机器学习算法中的梯度方法对于数据缩放和尺度都是很敏感的。
#所以在开始跑算法之前，应该进行归一化或者标准化的操作，使得特征数据缩放到0-1的范围中。
#数据特征缩放、归一化、标准化
from sklearn import preprocessing

In [120]:
#将数据随机分组为训练集和测试集
from sklearn.cross_validation import train_test_split

In [121]:
#交叉验证：一种充分利用样本的方法
#k折交叉验证：将样本集随机划分为k份，k-1份作为训练集，1份为验证集。
#依次轮换训练集和验证集k次，将验证误差最小的模型为最终模型。
#from sklearn.cross_validation import KFold

In [122]:
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report

In [123]:
#管道机制实现了对全部步骤的流式化封装和管理
from sklearn.pipeline import Pipeline

In [124]:
#GridSearchCV，它存在的意义就是自动调参，只要把参数输进去，就能给出最优化的结果和参数
#from sklearn.grid_search import GridSearchCV
from sklearn.model_selection import GridSearchCV

In [125]:
#BigBuckBuuny
df1 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-9/qoedata.csv')
df2 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-10/qoedata.csv')
df3 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-11/qoedata.csv')
df4 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-12/qoedata.csv')
#df5 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-13/qoedata.csv')
df6 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-14/qoedata.csv')
#df7 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-15/qoedata.csv')
#df8 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-17/qoedata.csv')
df9 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-18/qoedata.csv')
#df10 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-20/qoedata.csv')
df11 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-21/qoedata.csv')
df12 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-22/qoedata.csv')
#df13 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-23/qoedata.csv')
df14 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-24/qoedata.csv')
df15 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-25/qoedata.csv')

df16 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-26/qoedata.csv')
df17 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-27/qoedata.csv')
#df18 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-28/qoedata.csv')
df19 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-29/qoedata.csv')
#df20 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-30/qoedata.csv')
df21 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-31/qoedata.csv')
#df22 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-32/qoedata.csv')
#df23 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-33/qoedata.csv')
df24 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-34/qoedata.csv')
df25 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/BigBuckBunny/bola-35/qoedata.csv')
#df26 = pd.read_csv('/home/zdf/桌面/20181231/data/BigBuckBunny/bola-36/qoedata.csv')

#action
df27 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/action/action-1/qoedata.csv')
df28 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/action/action-2/qoedata.csv')
df29 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/action/action-3/qoedata.csv')
df30 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/action/action-4/qoedata.csv')
df31 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/action/action-7/qoedata.csv')

#doc
df32 = pd.read_csv('//Users/dave/Desktop/毕设数据/data/doc/doc-2/qoedata.csv')
df33 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/doc/doc-4/qoedata.csv')
df34 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/doc/doc-5/qoedata.csv')
df35 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/doc/doc-6/qoedata.csv')
df36 = pd.read_csv('//Users/dave/Desktop/毕设数据/data/doc/doc-7/qoedata.csv')

#dream
df37 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/dream/dream-1/qoedata.csv')
df38 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/dream/dream-3/qoedata.csv')
df39 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/dream/dream-4/qoedata.csv')
df40 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/dream/dream-5/qoedata.csv')

#flower
df41 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/flower/flower-2/qoedata.csv')
df42 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/flower/flower-3/qoedata.csv')
df43 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/flower/flower-4/qoedata.csv')
df44 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/flower/flower-6/qoedata.csv')

#future
#df45 = pd.read_csv('/home/zdf/桌面/20181231/data/future/future-1/qoedata.csv')
#df46 = pd.read_csv('/home/zdf/桌面/20181231/data/future/future-2/qoedata.csv')
#df47 = pd.read_csv('/home/zdf/桌面/20181231/data/future/future-3/qoedata.csv')
#df48 = pd.read_csv('/home/zdf/桌面/20181231/data/future/future-4/qoedata.csv')
df49 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/future/future-5/qoedata.csv')
df50 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/future/future-6/qoedata.csv')
df51 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/future/future-7/qoedata.csv')
df52 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/future/future-8/qoedata.csv')

#tv
df53 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/tv/tv-1/qoedata.csv')
df54 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/tv/tv-2/qoedata.csv')
df55 = pd.read_csv('/Users/dave/Desktop/毕设数据/data/tv/tv-3/qoedata.csv')

In [126]:
df  = pd.concat([df1,df2,df3,df4,df6,df9,
                 df11,df12,df14,df15,df16,df17,df19,
                 df21,df24,df27,df28,df29,df30,
                 df31,df32,df33,df34,df35,df36,df37,df38,df39,df40,
                 df41,df42,df43,df44], axis = 0)

In [127]:
print(len(df))

61120


In [128]:
df = df[df.state4 != 0]

In [129]:
print(len(df))

61042


In [130]:
df.to_csv("/Users/dave/Desktop/毕设数据/data/df-new.csv")

In [131]:
df[100:105]

Unnamed: 0  state4  state3  reqInterTime  downTraffic  downTrafficDiff  \
100         100       2       2       4.52282      1971522           340965   
101         101       2       2       4.52282      1971522           340965   
102         102       2       2       4.52282      1971522           340965   
103         103       2       2       4.52282      1971522           340965   
104         104       2       2       4.52282      1971522           340965   

     downTrafficDiffAbs  
100              340965  
101              340965  
102              340965  
103              340965  
104              340965

In [132]:
#DecisionTreeClassifier将输入两个数组：数组X，稀疏或密集，大小为[n_samples，n_features]，保存训练样本。
#以及整数值的数组Y，大小[n_samples]，持有类标签 训练样本
#从原数据表中提取一部分字段作为我们的特征X,对特征X进行OneHot编码。
X = df[['reqInterTime','downTraffic','downTrafficDiff','downTrafficDiffAbs']]
y = df['state4']
#y = df['state3']

In [133]:
# 标签转化
y = np.array(list(y))
#y = preprocessing.label_binarize(y, classes = [1,2,3,4])
#y = preprocessing.label_binarize(y, classes = [1,2,3])

In [134]:
#list和array的区别：array既可以通过索引值查找数据，也能够对整个数组进行数值运算。
#list无法对整个列表进行数值运算

#转换格式，制造样本集
#按照行遍历X表格，每次取一行转换为list格式，依次添加到样本点列表中
#然后将样本点列表转换为数组格式

samples = []
for i in range(len(X)):
    samples.append(list(X.iloc[i]))
samples = np.array(samples)

In [135]:
#数据归一化，缩放特征数据
samples = preprocessing.normalize(samples)
samples = samples.astype('float32')

In [136]:
X_train, X_test, y_train, y_test = train_test_split(samples, y, test_size=0.3, random_state=0)

In [137]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
rf0 = RandomForestClassifier(
                                bootstrap=True, 
                                class_weight='balanced', 
                                criterion='gini',
                                max_depth=None, 
                                max_features='auto', 
                                max_leaf_nodes=None,
                                min_impurity_decrease=0.0, 
                                min_impurity_split=None,
                                min_samples_leaf=1, 
                                min_samples_split=2,
                                min_weight_fraction_leaf=0.0, 
                                n_estimators=10, 
                                n_jobs=1,
                                oob_score=False, 
                                random_state=0, 
                                verbose=0, 
                                warm_start=False
                            )
rf0.fit(X_train, y_train)
y_pred = rf0.predict(X_test)
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          1       0.81      0.95      0.87      1166
          2       0.99      0.94      0.97     15413
          3       0.64      0.85      0.73      1133
          4       0.71      0.94      0.81       601

avg / total       0.95      0.94      0.94     18313



In [108]:
from sklearn .metrics import confusion_matrix
conmat = confusion_matrix(y_true = y_test, y_pred = y_pred)
print(conmat)
#print(confusion_matrix(y_test.argmax(axis=1), y_pred.argmax(axis=1)))

[[ 1103    33    12    18]
 [  234 14545   509   125]
 [    9    76   960    88]
 [   14     3    19   565]]
