In [3]:
import math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import ensemble
from sklearn import cross_validation
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn import preprocessing
from sklearn.preprocessing import PolynomialFeatures
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from astropy.units import Ybarn
from pylab import *
from matplotlib.ticker import MultipleLocator, FormatStrFormatter

gongzuobu = pd.read_csv('features_lable_final.csv')
gongzuobu

celebrity  userid  follow     fans  original_weibo  repost_weibo  \
0           0       1     316  3775598            2834           679   
1           2       3     393  4348114            4082          1164   
2           4       5     751   778999            4050          2285   
3           5       6     334  1241240            1351           766   
4           6       7     701  2498820            3772          1145   
5           7       8     442  3270155            2457          1126   
6           8       9     759  2295703            3605          1438   
7           9      10     181  5733434            2199           211   
8          11      12     475  3956210            1369           515   
9          12      13     202  6738735            2025           477   
10         13      14     802  2901026            2850           245   
11         14      15     429   660991            3005           586   
12         15      16     784  4966250            2120           408   
13         16      17     386  4599370            3238          1007   
14         17      18     827  5873421            7514          3470   
15         18      19     249  1615138            2006           530   
16         19      20     224  2203402            2572          2398   
17         20      21     183  2879664            1970           937   
18         21      22     567   502984            1316           142   
19         22      23     147   387598             589           244   
20         23      24     768  1358200             794           155   
21         24      25     695  4095687            2108           553   
22         26      27     458    84325             766            44   
23         27      28     509   346674            1673           554   
24         28      29     281  2010240            1825           171   
25         31      32     277    11725             397           151   
26         32      33     219   513576             301           368   
27         33      34     464    53265             889           169   
28         34      35     391   929991            1255           591   
29         36      37     266   613758             606            28   
..        ...     ...     ...      ...             ...           ...   
54         72      73     563  1645795             785           126   
55         74      75     349  5012064            1690           123   
56         75      76     515   613343            4030          1876   
57         76      77      73   363566            3088          1539   
58         78      79    1131   950432            5578          4167   
59         79      80      63  1558363            1105            52   
60         80      81     561  3281826            1627           457   
61         81      82     582   966023            4596           701   
62         82      83     181   620339            1258           591   
63         83      84     967   978416            3907           746   
64         84      85     262  3660599            1879           225   
65         85      86     370  1169908             985             7   
66         86      87     363   948803            3379           947   
67         87      88     275  1719900            3280           382   
68         88      89     218   250745             330            61   
69         89      90     897  1181707            2668          1167   
70         90      91    1355  1610157            3688           622   
71         91      92     288    74641             897           355   
72         92      93     181   845670            1552            37   
73         93      94     597    20979            1079           122   
74         94      95     110   196397            1496           516   
75         95      96     433   484783            1851           567   
76         96      97    1069  1009730            3395          1433   
77         98      99     393  6301549      

In [ ]:
'product_comm_sent','neg_com_perc','ave_price','price_var','update','turnover_month_appr',

In [12]:
X = gongzuobu[[
               'product_comm_sent','neg_com_perc','ave_price','price_var','update',
               'original_weibo','repost_weibo','like_weibo','fans','av_comment','av_like','av_repost','follow'
               ]]
y = gongzuobu[['sales_month']]
#X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 1)
X_train, X_test, y_train, y_test = cross_validation.train_test_split(X,y, test_size=0.4, random_state=0)
forest = RandomForestRegressor(n_estimators = 100,criterion='mse',
                                      random_state=1,n_jobs=-1)
forest.fit(X_train, y_train)
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)

c:\users\yee shen\appdata\local\programs\python\python35\lib\site-packages\ipykernel_launcher.py:10: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  # Remove the CWD from sys.path while we load stuff.


In [13]:
y_test_pred

array([ 20843.09,  43432.26,  33460.4 , 203013.26,  43187.95,  59758.15,
        29243.2 ,  12040.02,  31012.67,  82515.74,  77478.24,  50772.19,
        11096.01,  75293.05,  77314.64,  31023.54,   5813.21,  44648.28,
        86172.84,  14960.77,  12264.34,   8105.8 ,  13611.8 ,  18681.44,
       116920.8 ,  12978.68,  15675.25,  40662.08,  50006.16,  20120.57,
        25685.76, 237303.17,   6319.7 ,  17088.63])

In [15]:
print('R^2 train: %.3f, test: %.3f' % (r2_score(y_train, y_train_pred),
                                   r2_score(y_test, y_test_pred)))

R^2 train: 0.905, test: 0.007


In [8]:
importances = forest.feature_importances_
std = np.std([tree.feature_importances_ for tree in forest.estimators_],
             axis=0)
indices = np.argsort(importances)[::-1]

# Print the feature ranking
print("Feature ranking:")

for f in range(X.shape[1]):
    print("%d. feature %d (%f)" % (f + 1, indices[f], importances[indices[f]]))

Feature ranking:
1. feature 3 (0.333030)
2. feature 5 (0.184619)
3. feature 7 (0.122407)
4. feature 0 (0.101971)
5. feature 2 (0.096621)
6. feature 6 (0.064018)
7. feature 4 (0.056370)
8. feature 1 (0.040964)


In [6]:
a=range(35)
ymajorLocator  = MultipleLocator(50000)
xmajorLocator  = MultipleLocator(1)
ax = subplot()
ax.yaxis.set_major_locator(ymajorLocator)
ax.xaxis.set_major_locator(xmajorLocator)
plt.plot(a,y_test,'b-')
plt.plot(a,y_test_pred,'g-')
plt.ylabel('sales_month')
plt.show()

In [7]:
# Plot the feature importances of the forest
plt.figure()
plt.title("Feature importances")
plt.bar(range(X.shape[1]), importances[indices],
       color="r")
plt.xticks(range(X.shape[1]), indices)
plt.xlim([-1, X.shape[1]])
plt.show()

In [8]:
indices

array([ 5,  0,  2, 11,  7, 12,  1,  9,  8,  6, 10, 13, 14,  3,  4], dtype=int64)

In [9]:
importances

array([ 0.09731009,  0.01203882,  0.04055452,  0.00405685,  0.0010809 ,
        0.73053269,  0.00727716,  0.02078427,  0.00751262,  0.01063894,
        0.00604261,  0.03594167,  0.01608298,  0.00540991,  0.00473598])

<module 'numpy' from 'D:\\Professional software\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>